defaults:
    - override hydra/hydra_logging: none
    - override hydra/job_logging: none

training:
    device: gpu
    dataset_path: /home/xuexiangyuan/data/face-swap
    checkpoint_path: ./checkpoint/training_${now:%Y%m%d%H%M%S}
    batch_size: 16
    num_workers: 16
    learning_rate: 4e-4
    loss_function:
        weight_adversarial: 1
        weight_attribute: 5
        weight_identity: 20
        weight_reconstruction: 5
    num_iterations: 500000
    report_interval: 100
    save_interval: 10000

image_inference:
    device: gpu
    generator_path: ./checkpoint/training_20231125142041/iteration_20000/generator.pth
    source_image_path: ./temp/image/4.jpeg
    target_image_path: ./temp/image/2.jpg
    result_image_save_path: ./temp/result/1.jpg


hydra:
    run:
        dir: ${training.checkpoint_path}
    sweep:
        dir: ${training.checkpoint_path}
